### ISSUE TITLE
Mistake found in SSH key related file

### ISSUE THREAD

**Issue by Fengyee** [missing-semester-cn/missing-semester-cn.github.io#152]
At this location: https://github.com/missing-semester-cn/missing-semester-cn.github.io/blob/master/_2020/command-line.md#%E5%9F%BA%E4%BA%8E%E5%AF%86%E9%92%A5%E7%9A%84%E8%AE%A4%E8%AF%81%E6%9C%BA%E5%88%B6,

the private key is copied to the remote server. It should be

```bash
cat .ssh/id_ed25519.pub | ssh foobar@remote 'cat >> ~/.ssh/authorized_keys'
```

**Comment by hanxiaomax** [comment]
Thank you. please can you fix it and create a PR?

**Comment by Fengyee** [comment]
PR created.
