### ISSUE TITLE
I would like to translate editors.md

### ISSUE THREAD

**Issue by le0tan** [missing-semester-cn/missing-semester-cn.github.io#23]
Filename: editors.md
Estimated time of finish: June 7, 2020

Note: Please make sure you can finish it within two weeks.

(looks like it's been more than two weeks since this file is claimed, is it OK if I finish the rest?)

**Comment by hanxiaomax** [comment]
Yeah. I agree with you, the rules should always be followed. But when he claimed this file, we actually didnt have this rule yet. To be fair, Let me ask him for updates. if there is no reply, you can go with it. we wait for another day, is that ok for you ：）

**Comment by le0tan** [comment]
@hanxiaomax sure no prob

**Comment by hanxiaomax** [comment]
#1 still working on it

**Comment by hanxiaomax** [comment]
#1 finished
