### ISSUE TITLE
Enhancement: Web lectures on other platforms

### ISSUE THREAD

**Issue by ziranl16** [missing-semester-cn/missing-semester-cn.github.io#77]
The current web lectures are hosted on YouTube, which may not be very convenient sometimes.

**_If the original authors give informed consent in terms of copyright/license_**, it might be better if we can also host the web lectures with the subtitles on other platforms(such as Bilibili) as well.

**Comment by hanxiaomax** [comment]
Actually they are everywhere, especially on Bilibili :). And people who working on the subtitles also hosting theirs.

**Comment by ziranl16** [comment]
Noted with thanks. : )
